- name: Config Plasma
  ansible.builtin.import_tasks: plasma.yml

- name: Config Konsole
  ansible.builtin.import_tasks: konsole.yml
  tags: konsole

- name: Config Kwallet
  ansible.builtin.import_tasks: kwallet.yml
  tags: kwallet

- name: Config libinput-gestures
  ansible.builtin.import_tasks: libinput-gestures.yml
  tags: libinput-gestures

- name: Config logiops
  ansible.builtin.import_tasks: logiops.yml
  tags: logiops
