- name: Restart logiops
  become: true
  become_user: root
  ansible.builtin.service:
    name: logid.service
    state: restarted
  listen: restart logiops

- name: Notify Easyeffects
  ansible.builtin.debug:
    msg: Remember to add Easyeffects to autostart via application
  listen: easyeffects installed
