- name: Install Distro Software
  become: true
  become_user: root
  ansible.builtin.dnf:
    name:
      - ark
      - kate
      - plasma-browser-integration
      - usbmuxd
      - libimobiledevice
      - "@Virtualization"

- name: Install Docker
  ansible.builtin.import_tasks: docker.yml
  tags: docker

- name: Install Chrome
  ansible.builtin.import_tasks: chrome.yml

- name: Install VSCode
  ansible.builtin.import_tasks: chrome.yml

- name: Install Jetbrains
  ansible.builtin.import_tasks: jetbrains.yml
  tags: jetbrains

- name: Install NVM
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm.git
    # renovate datasource=github-tags repo=nvm-sh/nvm
    version: v0.39.5
    dest: "/home/{{ ansible_user_id }}/.nvm"
    depth: 1
  tags: nvm

- name: Install Software via DNF
  become: true
  become_user: root
  ansible.builtin.dnf:
    name:
      - vim
      - telegram-desktop
      - yubikey-manager-qt
      - yubioath-desktop
      - libreoffice
      - buildah
      - podman
      - conda
      - gh
      - https://github.com/aquasecurity/trivy/releases/download/v0.41.0/trivy_0.41.0_Linux-64bit.rpm
      - https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.rpm

- name: Install Software via flatpak
  community.general.flatpak:
    name:
      - com.spotify.Client
      - com.mattermost.Desktop
      - com.getpostman.Postman
      - rest.insomnia.Insomnia
