name: dotfiles
channels:
  - defaults
  - conda-forge
dependencies:
  # renovate datasource=conda depName=conda-forge/ansible-lint
  - ansible-lint=6.17.2
  # renovate datasource=conda depName=conda-forge/ansible-core
  - ansible-core=2.15.1
  - python=3.9
