- name: Install GPG
  community.general.pacman:
    name: gnupg
  when: ansible_pkg_mgr == "pacman"
  become: true

- name: Check if GPG key exists
  environment:
    GNUPGHOME: "/home/{{ ansible_user_id }}/.gnupg"
  ansible.builtin.shell:
    cmd: gpg --list-secret-keys --keyid-format=long | grep "{{ item }}"
  register: gpg_key
  changed_when: gpg_key.rc == 1
  failed_when: gpg_key.rc > 1
  check_mode: false
  notify: 'import gpg keys'
  loop:
    - "91CCDCB31830CD1B220E562808EC00F294397A62$"
    - "0DB075853AE070032B8A74D164F15A83A08C982F$"
