- name: Install needed software
  become: true
  become_user: root
  ansible.builtin.dnf:
    name:
      - git
      - zsh

- name: Clone ohmyzsh/ohmyzsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ ansible_user_id }}/.oh-my-zsh"
    depth: 1

- name: Copy OhMyZsh Configuration
  ansible.builtin.template:
    src: .zshrc.j2
    dest: "/home/{{ ansible_user_id }}/.zshrc"
    mode: "0600"

- name: Clone powerlevel10k/powerlevel10k # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    # renovate datasource=github-tags repo=romkatv/powerlevel10k
    version: v1.18.0
    dest: "/home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Copy Powerlevel10k Configuration
  ansible.builtin.copy:
    src: .p10k.zsh
    dest: "/home/{{ ansible_user_id }}/.p10k.zsh"
    mode: "0644"

- name: Add Git configuration
  ansible.builtin.copy:
    src: ".gitconfig"
    dest: "/home/{{ ansible_user_id }}/.gitconfig"
    mode: "0600"

- name: Setup SSH
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh

- name: Setup GPG
  ansible.builtin.import_tasks: gpg.yml
  tags: gpg
