- name: User Shell
  ansible.builtin.import_tasks: user.yml

- name: Setup SSH
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh

- name: Setup GNUPG
  ansible.builtin.import_tasks: gnupg.yml
  tags: gnupg
