- name: Install konsole and fonts
  when: ansible_pkg_mgr == "pacman"
  become: true
  community.general.pacman:
    name:
      - konsole
      - ttf-meslo-nerd

- name: Set folder structure
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/{{ item }}"
    state: directory
    mode: 0700
  loop:
    - ".local/share/konsole"
    - ".config"

- name: Copy default profile
  ansible.builtin.copy:
    src: konsole/profile
    dest: "/home/{{ ansible_user_id }}/.local/share/konsole/Tommaso.profile"
    mode: 0600

- name: Set default profile
  community.general.ini_file:
    path: "/home/{{ ansible_user_id }}/.config/konsolerc"
    section: "Desktop Entry"
    option: DefaultProfile
    value: Tommaso.profile
    mode: 0600
    no_extra_spaces: true
