- name: Install kwallet
  when: ansible_pkg_mgr == "pacman"
  become: true
  block:
    - name: Install requirements
      community.general.pacman:
        name:
          - openssh
          - kwallet
          - kwallet-pam
          - ksshaskpass

    - name: Install AUR requirements
      kewlfft.aur.aur:
        name: kwalletcli
      become_user: aur_builder

- name: Set user folder structure
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/{{ item }}"
    state: directory
    mode: 0700
  loop:
    - ".gnupg"
    - ".config/systemd/user"
    - ".config/environment.d"

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user_id }}/{{ item.dest }}"
    mode: 0600
  loop:
    - { src: "kwallet/ssh/ssh-agent.service", dest: ".config/systemd/user/ssh-agent.service" }
    - { src: "kwallet/ssh/ssh-add.desktop", dest: ".config/autostart/ssh-add.desktop" }
    - { src: "kwallet/ssh/ssh_askpass.conf", dest: ".config/environment.d/ssh_askpass.conf" }
    - { src: "kwallet/gnupg/gpg-agent.conf", dest: ".gnupg/gpg-agent.conf" }

- name: Enable SSH-Agent for current user
  ansible.builtin.systemd:
    name: ssh-agent
    enabled: true
    daemon_reload: true
    scope: user
