- name: Config Plasma
  ansible.builtin.import_tasks: plasma.yml

- name: Config Konsole
  ansible.builtin.import_tasks: konsole.yml

- name: Config Kwallet
  ansible.builtin.import_tasks: kwallet.yml
