- name: Handle Pacman DE installation
  become: true
  when: ansible_pkg_mgr == "pacman"
  block:
    - name: Install Desktop Environment and applications
      community.general.pacman:
        name:
          - plasma-meta
          - ark
          - dolphin
          - kate
          - spectacle

    - name: Install optional application deps as deps
      community.general.pacman:
        name:
          - unrar
          - unarchiver
          - ffmpegthumbs
          - kdegraphics-thumbnailers
        reason: dependency

- name: Plasma configuration
  notify: 'restart sddm'
  block:
    - name: Set global configuration
      community.general.ini_file:
        path: "/home/{{ ansible_user_id }}/.config/kdeglobals"
        section: KDE
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: 0644
        no_extra_spaces: true
      loop:
        - { option: "LookAndFeelPackage", value: "org.kde.breezedark.desktop" }
        - { option: "SingleClick", value: "false" }

    - name: Set virtual Desktops
      community.general.ini_file:
        path: "/home/{{ ansible_user_id }}/.config/kwinrc"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: 0644
        no_extra_spaces: true
      loop:
        - { section: "Desktops", option: "Number", value: "6" }
        - { section: "Desktops", option: "Rows", value: "2" }
        - { section: "Windows", option: "RollOverDesktops", value: "true" }

    - name: Set keyboard layout for KDE
      community.general.ini_file:
        path: "/home/{{ ansible_user_id }}/.config/kxkbrc"
        section: Layout
        option: "Model"
        value: "dell"
        mode: 0644
        no_extra_spaces: true

    - name: Configure Modules
      community.general.ini_file:
        path: "/home/{{ ansible_user_id }}/.config/kded5rc"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: 0644
        no_extra_spaces: true
      loop:
        - { section: "Module-browserintegrationreminder", option: "autoload", value: "false" }
        - { section: "Module-device_automounter", option: "autoload", value: "false" }

    - name: Set Default shutdown option
      community.general.ini_file:
        path: "/home/{{ ansible_user_id }}/.config/ksmserverrc"
        section: General
        option: shutdownType
        value: "2"
        mode: 0644
        no_extra_spaces: true

    - name: Set Default Keybindings
      community.general.ini_file:
        path: "/home/{{ ansible_user_id }}/.config/kglobalshortcutsrc"
        section: "kwin"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: 0644
        no_extra_spaces: true
      loop:
        - { option: "Switch One Desktop Down", value: "Meta+Ctrl+Down,Meta+Ctrl+Down,Switch One Desktop Down" }
        - { option: "Switch One Desktop Up", value: "Meta+Ctrl+Up,Meta+Ctrl+Up,Switch One Desktop Up" }
        - { option: "Switch One Desktop to the Left", value: "Meta+Ctrl+Left,Meta+Ctrl+Left,Switch One Desktop to the Left" }
        - { option: "Switch One Desktop to the Right", value: "Meta+Ctrl+Right,Meta+Ctrl+Right,Switch One Desktop to the Right" }
        - { option: "Window One Desktop Down", value: "Meta+Ctrl+Shift+Down,Meta+Ctrl+Shift+Down,Window One Desktop Down" }
        - { option: "Window One Desktop Up", value: "Meta+Ctrl+Shift+Up,Meta+Ctrl+Shift+Up,Window One Desktop Up" }
        - { option: "Window One Desktop to the Left", value: "Meta+Ctrl+Shift+Left,Meta+Ctrl+Shift+Left,Window One Desktop to the Left" }
        - { option: "Window One Desktop to the Right", value: "Meta+Ctrl+Shift+Right,Meta+Ctrl+Shift+Right,Window One Desktop to the Right" }
