- name: Set Hostname
  ansible.builtin.hostname:
    name: "{{ system.hostname }}"
  when: system.hostname is defined

- name: Set time zone
  community.general.timezone:
    name: Europe/Rome
  notify:
    - "sync time"

- name: Set vconsole keymap
  ansible.builtin.lineinfile:
    path: /etc/vconsole.conf
    line: "KEYMAP={{ system.keymap }}"
    create: true
    mode: 0644
  when: system.keymap is defined

- name: Ensure locale is present
  community.general.locale_gen:
    name: "{{ item }}"
  loop:
    - en_US.UTF-8
    - it_IT.UTF-8

- name: Set locale.conf
  ansible.builtin.copy:
    src: etc/locale.conf
    dest: /etc/locale.conf
    mode: 0644

- name: Set Machine Info
  ansible.builtin.template:
    src: etc/machine-info.j2
    dest: /etc/machine-info
    mode: 0644
  when: system.pretty_hostname is defined

- name: Increase number of login tries to 10
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    line: "deny = 10"

- name: Install user requirements
  community.general.pacman:
    name: sudo
  when: ansible_pkg_mgr == "pacman"

- name: Add wheel Group
  ansible.builtin.group:
    name: wheel

- name: Wheel group can use sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: "visudo -cf %s"
