sddm_service: sddm-plymouth.service

keybindings:
  - { option: "Window to Next Screen", value: "Meta+Shift+Right,Meta+Shift+Right,Window to Next Screen" }
  - { option: "Window to Previous Screen", value: "Meta+Shift+Left,Meta+Shift+Left,Window to Previous Screen" }
  - { option: "Switch One Desktop Down", value: "Meta+Ctrl+Down,Meta+Ctrl+Down,Switch One Desktop Down" }
  - { option: "Switch One Desktop Up", value: "Meta+Ctrl+Up,Meta+Ctrl+Up,Switch One Desktop Up" }
  - { option: "Switch One Desktop to the Left", value: "Meta+Ctrl+Left,Meta+Ctrl+Left,Switch One Desktop to the Left" }
  - { option: "Switch One Desktop to the Right", value: "Meta+Ctrl+Right,Meta+Ctrl+Right,Switch One Desktop to the Right" }
  - { option: "Window One Desktop Down", value: "Meta+Ctrl+Shift+Down,Meta+Ctrl+Shift+Down,Window One Desktop Down" }
  - { option: "Window One Desktop Up", value: "Meta+Ctrl+Shift+Up,Meta+Ctrl+Shift+Up,Window One Desktop Up" }
  - { option: "Window One Desktop to the Left", value: "Meta+Ctrl+Shift+Left,Meta+Ctrl+Shift+Left,Window One Desktop to the Left" }
  - { option: "Window One Desktop to the Right", value: "Meta+Ctrl+Shift+Right,Meta+Ctrl+Shift+Right,Window One Desktop to the Right" }
