- name: Install TLP
  community.general.pacman:
    name:
      - tlp
  when: ansible_pkg_mgr == "pacman"
  become: true

- name: Enable TLP service
  ansible.builtin.systemd:
    name: tlp.service
    enabled: true
    state: started
  become: true

- name: Disable rfkill services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
    masked: true
  become: true
  loop:
    - systemd-rfkill.service
    - systemd-rfkill.socket
