- name: Power management
  become: true
  become_user: root
  block:
    - name: Uninstall power-profiles-daemon
      ansible.builtin.dnf:
        name:
          - power-profiles-daemon
        state: removed

    - name: Install TLP
      ansible.builtin.dnf:
        name:
          - tlp

    - name: Enable TLP
      ansible.builtin.service:
        name: tlp
        state: started
        enabled: true

    - name: Mask rfkill
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
      loop:
        - systemd-rfkill.service
        - systemd-rfkill.socket

- name: Intel Hardware acceleration
  become: true
  become_user: root
  when: intel_cpu and hardware_acceleration
  block:
    - name: Install Intel Drivers and tools
      ansible.builtin.dnf:
        name:
          - intel-gpu-tools
          - libva-utils
          - intel-media-driver

    - name: Force LIBVA_DRIVER_NAME to iHD
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "LIBVA_DRIVER_NAME=iHD"
