- name: Fingerprint Installation
  when: ansible_pkg_mgr == "pacman"
  block:
    - name: Fingerprint drivers
      kewlfft.aur.aur:
        name:
          - libfprint-tod-git
          - libfprint-2-tod1-xps9300-bin
      become: true
      become_user: "{{ aur_helper }}"

    - name: Fingerprint software
      community.general.pacman:
        name:
          - fprintd
          - imagemagick

- name: Add user to input group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups:
      - input
    append: true

- name: Install PulseAudio
  community.general.pacman:
    name: pulseaudio
  when: ansible_pkg_mgr == "pacman"

- name: Add Pulseaudio config folder
  ansible.builtin.file:
    path: /etc/pulse/default.pa.d
    state: directory
    mode: 0755

- name: Add Microphone Cancellation
  ansible.builtin.copy:
    src: noise-cancellation.pa
    dest: /etc/pulse/default.pa.d/noise-cancellation.pa
    mode: 0644
  notify: "restart pulseaudio"
