- name: Setup Docker
  become: true
  block:
    - name: Install Docker
      community.general.pacman:
        name:
          - docker
          - docker-compose
          - docker-buildx
      when: ansible_pkg_mgr == "pacman"

    - name: Add docker Group
      ansible.builtin.group:
        name: docker

    - name: Add user to docker Group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        append: true
        groups:
          - docker

    - name: Enable Native Diff Engine
      ansible.builtin.copy:
        src: disable-overlay-redirect-dir.conf
        dest: /etc/modprobe.d/disable-overlay-redirect-dir.conf
        mode: 0644
      when: ansible_os_family == "Archlinux"
      notify: 'overlay modprobe changed'

    - name: Copy Docker Configuration
      ansible.builtin.copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
        mode: 0644
      notify: 'docker config changed'

    - name: Start Docker Service
      ansible.builtin.service:
        name: docker
        enabled: true

- name: Login Docker
  community.docker.docker_login:
    username: "{{ docker.username }}"
    password: "{{ docker.password }}"
  when: docker is defined
