- name: Install SSH agent
  community.general.pacman:
    name: openssh
  when: ansible_pkg_mgr == "pacman"

- name: Structure for user systemd
  ansible.builtin.file:
    path: "/home/{{ user['name'] }}/.config/systemd/user"
    state: directory
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    mode: 0755

- name: Add user SSH agent
  ansible.builtin.copy:
    src: home/config/systemd/user/ssh-agent.service
    dest: "/home/{{ user['name'] }}/.config/systemd/user/ssh-agent.service"
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    mode: 0644

- name: Get passwd entries for default user
  ansible.builtin.getent:
    database: passwd
    key: "{{ user['name'] }}"

- name: Enable SSH Agent service
  ansible.builtin.systemd:
    name: ssh-agent.service
    enabled: true
    scope: user
  become_user: "{{ user['name'] }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[user['name']].1 }}"

- name: Structure for user systemd
  ansible.builtin.file:
    path: "/home/{{ user['name'] }}/.config/autostart"
    state: directory
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    mode: 0755

- name: Copy ssh-add desktop runner
  ansible.builtin.copy:
    src: home/config/autostart/ssh-add.desktop
    dest: "/home/{{ user['name'] }}/.config/autostart/ssh-add.desktop"
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    mode: 0644

- name: Install ksshaskpass
  community.general.pacman:
    name: ksshaskpass
  when: ansible_pkg_mgr == "pacman"

- name: Structure for environment.d
  ansible.builtin.file:
    path: "/home/{{ user['name'] }}/.config/environment.d"
    state: directory
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    mode: 0755

- name: Copy default askpass agent
  ansible.builtin.copy:
    src: home/config/environment.d/ssh_askpass.conf
    dest: "/home/{{ user['name'] }}/.config/environment.d/ssh_askpass.conf"
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    mode: 0644
