- name: Base Software
  community.general.pacman:
    name:
      - git
      - zsh
  when: ansible_pkg_mgr == "pacman"

- name: Create default user
  ansible.builtin.user:
    comment: "{{ user['comment'] }}"
    name: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    groups: wheel
    append: true
    password: "{{ user['password'] }}"
    update_password: on_create
    shell: /usr/bin/zsh

- name: Add Git Personal configuration
  ansible.builtin.copy:
    src: "home/git/gitconfig"
    dest: "/home/{{ user['name'] }}/.gitconfig"
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    mode: 0600

- name: Add Git Work configuration
  ansible.builtin.copy:
    src: "home/git/gitconfig.nethesis"
    dest: "/home/{{ user['name'] }}/.gitconfig.nethesis"
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    mode: 0600

- name: Clone ohmyzsh/ohmyzsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{ user['name'] }}/.oh-my-zsh
    depth: 1
  become_user: "{{ user['name'] }}"

- name: Clone powerlevel10k/powerlevel10k # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/{{ user['name'] }}/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
  become_user: "{{ user['name'] }}"

- name: Copy .zshrc
  ansible.builtin.copy:
    src: "home/zshrc"
    dest: "/home/{{ user['name'] }}/.zshrc"
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    mode: 0644

- name: Copy .p10k.zsh
  ansible.builtin.copy:
    src: "home/p10k.zsh"
    dest: "/home/{{ user['name'] }}/.p10k.zsh"
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"
    mode: 0644
